// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountsAPI 账号管理API
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Checkin 手动触发签到任务：结果如实反映本应用实际做到的事（未接入上游即 skipped）
 */
export function Checkin(uids: string[] | null): $CancellablePromise<core$0.TaskRun | null> {
    return $Call.ByID(2963933235, uids);
}

/**
 * ClientSession 官方客户端当前登录账号探测（账号管理页提示条数据源）：
 * 从官方登录位读当前登录 uid（明文），并在 client_auth_dirs 发现目录里找
 * 同 uid 的可用明文凭证。只读磁盘，可安全频繁调用。
 */
export function ClientSession(): $CancellablePromise<core$0.ClientSession | null> {
    return $Call.ByID(3770010829);
}

/**
 * Delete 删除账号：移除其凭证文件（auth_dir 是该账号的唯一真实来源）
 */
export function Delete(uid: string): $CancellablePromise<void> {
    return $Call.ByID(1427742879, uid);
}

/**
 * Detail 账号详情（凭证快照 + 本地运行态）
 */
export function Detail(uid: string): $CancellablePromise<core$0.Account | null> {
    return $Call.ByID(1522372805, uid);
}

/**
 * ExportCredentials 弹出系统保存对话框，把全部凭证写入用户选择的位置。
 * password 非空时输出加密信封（AES-256-GCM + PBKDF2，密码不写入文件）；
 * 为空时保持 v1 明文导出（前端会提示明文风险）。
 */
export function ExportCredentials(password: string): $CancellablePromise<$models.CredentialExportResult | null> {
    return $Call.ByID(2234793956, password);
}

/**
 * FocusMainWindow 把主窗口带回前台（授权成功时提示用）。
 */
export function FocusMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(4020263129);
}

/**
 * ImportClientSession 一键导入客户端当前登录账号：把发现的明文凭证复制进
 * auth_dir（不移动原文件，官方登录位里的加密 token 不做也不需要解密）。
 */
export function ImportClientSession(): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByID(3138577430);
}

/**
 * ImportCredentials 导入凭证内容到 auth_dir；支持单个对象或对象数组，
 * 也支持 v2 加密导出信封（此时必须提供导出时的 password）。
 */
export function ImportCredentials(fileName: string, content: string, password: string): $CancellablePromise<$models.ImportResult | null> {
    return $Call.ByID(1256028573, fileName, content, password);
}

/**
 * List 账号列表：唯一来源是 auth_dir 下的真实凭证文件，服务端过滤 + 分页。
 */
export function List(q: $models.AccountQuery): $CancellablePromise<$models.AccountListResult | null> {
    return $Call.ByID(2380172540, q);
}

/**
 * OpenAuthDir 在系统文件管理器中打开凭证目录，返回目录绝对路径
 */
export function OpenAuthDir(): $CancellablePromise<string> {
    return $Call.ByID(121782201);
}

/**
 * OpenLoginWindow 在应用内开一个 WebView 窗口加载官方授权页：手机号+短信登录
 * 可以完全在应用内完成，不碰系统浏览器（state 轮询与登录页面互相独立，不受影响）。
 * 只允许打开当前会话签发的 authUrl，不接受前端传任意 URL。
 */
export function OpenLoginWindow(region: string): $CancellablePromise<void> {
    return $Call.ByID(216840441, region);
}

/**
 * OpenURL 用系统浏览器打开外部链接
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(856339245, url);
}

/**
 * PollOAuth 轮询授权状态；完成时把凭证写入 auth_dir 并广播账号事件。
 * globalRegion：国际版账号的地区代码（如 HK）。国际版新号必须先完成地区注册，
 * 否则聊天报 14017；地区由用户在弹窗里选，这里只负责提交，不替他决定。
 * 落盘失败时不删除会话（issue #26 同款教训）：state 上游仍有效，前端重试轮询
 * 可直接再走落盘，不会把「落盘失败」误报成「二维码已失效」。
 */
export function PollOAuth(region: string, globalRegion: string): $CancellablePromise<$models.OAuthPollResult | null> {
    return $Call.ByID(1168863464, region, globalRegion);
}

/**
 * RefreshCredit 立即查询指定账号的真实积分余额（按需触发，不等 keepalive 周期），
 * 返回刷新后的账号视图。
 */
export function RefreshCredit(uid: string): $CancellablePromise<core$0.Account | null> {
    return $Call.ByID(827740222, uid);
}

/**
 * RunTask 手动触发任意任务（checkin / travel / keepalive / activity / school / cat / growth）
 */
export function RunTask(taskType: string, uids: string[] | null): $CancellablePromise<core$0.TaskRun | null> {
    return $Call.ByID(3672346976, taskType, uids);
}

/**
 * RunTaskAsync 异步触发任务：提交后立即返回，不阻塞前端；任务在后台执行，
 * 完成时通过 task:completed 事件广播（运行记录见调度器 Status 的 lastRun）。
 * 同类任务已有执行未结束时调度器会自动跳过本次（结果里如实标注 skipped）。
 */
export function RunTaskAsync(taskType: string, uids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2051860868, taskType, uids);
}

/**
 * SetDisabled 设置账号禁用/启用（禁用后不参与网关选号与定时任务）
 */
export function SetDisabled(uid: string, disabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1057225668, uid, disabled);
}

/**
 * StartOAuth 发起设备授权：请求上游签发 state，返回官方授权页地址（authUrl）。
 * 用户在浏览器完成登录后，前端轮询 PollOAuth 检测结果并自动落盘凭证。
 */
export function StartOAuth(region: string): $CancellablePromise<$models.OAuthHint | null> {
    return $Call.ByID(3781023231, region);
}

/**
 * TaskStatus 调度器状态（含各任务下次执行时间与最近运行记录）
 */
export function TaskStatus(): $CancellablePromise<core$0.SchedulerStatus | null> {
    return $Call.ByID(2861919955);
}
