// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentsAPI 智能体一键接入API：探测本机 AI 编程客户端并写入网关配置
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply 接入指定客户端（写入前自动备份）
 */
export function Apply(params: $models.ApplyParams): $CancellablePromise<core$0.AgentApplyResult | null> {
    return $Call.ByID(2079763130, params);
}

/**
 * Backups 列出某客户端的备份
 */
export function Backups(target: string): $CancellablePromise<core$0.AgentBackup[] | null> {
    return $Call.ByID(2092225317, target);
}

/**
 * List 探测全部支持的客户端
 */
export function List(): $CancellablePromise<core$0.AgentTarget[] | null> {
    return $Call.ByID(3296815150);
}

/**
 * Restore 回滚指定备份，返回恢复的文件数
 */
export function Restore(target: string, backupID: string): $CancellablePromise<number> {
    return $Call.ByID(1304802584, target, backupID);
}
