// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoStartAPI 开机自启控制
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * Set 开启 / 关闭开机自启（下次登录系统时生效）
 */
export function Set(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(380919003, on);
}

/**
 * Status 查询开机自启真实状态（由系统注册状态推导）
 */
export function Status(): $CancellablePromise<core$0.AutoStartStatus> {
    return $Call.ByID(2167692855);
}
