// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatAPI 聊天测试API。
 * 
 * 不是本地直造回复：它把请求**真实地**发到本机网关的 /v1/chat/completions，
 * 因此「聊天测试」跑的是完整链路——鉴权、配额、账号路由、记账、日志一个不漏。
 * 网关不可用或账号池为空时，错误原样返回给界面。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Abort 停止当前进行中的对话；返回是否有对话被停止。
 */
export function Abort(): $CancellablePromise<boolean> {
    return $Call.ByID(925020668);
}

/**
 * Send 发送消息：流式时逐段通过 chat:token / chat:reasoning 事件推送，结束发 chat:done。
 * 同一时刻只允许一条进行中的对话；Abort 可随时取消（已生成内容保留并随结果返回）。
 */
export function Send(params: $models.ChatParams): $CancellablePromise<$models.ChatResult | null> {
    return $Call.ByID(4183916264, params);
}
