// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ClientSwitchAPI 官方客户端登录账号切换
 * （把账号池中的凭证写入官方登录位并重启客户端，进度经 clientswitch:progress 事件回报）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * Backups 列出切换时自动备份的官方登录文件（可手工还原）
 */
export function Backups(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(4103624650);
}

/**
 * Precheck 切换前检查：目标账号 / 官方登录位状态 / 客户端探测 / 跨通道警告
 */
export function Precheck(uid: string): $CancellablePromise<core$0.ClientSwitchPrecheck | null> {
    return $Call.ByID(1776501272, uid);
}

/**
 * Switch 执行切换（备份 → 退出客户端 → 写入登录位 → 重启客户端）。
 * 同步执行；每步进度经 clientswitch:progress 事件推送前端。
 */
export function Switch(uid: string): $CancellablePromise<void> {
    return $Call.ByID(3178885831, uid);
}
