// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigAPI 配置管理API
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Backup 备份配置，返回备份文件路径
 */
export function Backup(): $CancellablePromise<string> {
    return $Call.ByID(1635836372);
}

/**
 * Defaults 返回默认配置（含随机生成的根密钥），供「恢复默认」使用。
 * 默认值由后端单点定义，前端不再自行拼一份硬编码配置。
 */
export function Defaults(): $CancellablePromise<$models.GatewayConfig | null> {
    return $Call.ByID(4150722724);
}

/**
 * Export 弹出系统保存对话框，把配置写入用户选择的位置。
 * includeCredentials 时把登录凭证一并打包成合并包（password 非空则 AES-256-GCM 加密信封）。
 */
export function Export(includeCredentials: boolean, password: string): $CancellablePromise<$models.ConfigExportResult | null> {
    return $Call.ByID(1614520592, includeCredentials, password);
}

/**
 * Get 获取当前配置
 */
export function Get(): $CancellablePromise<$models.GatewayConfig | null> {
    return $Call.ByID(1830719198);
}

/**
 * Import 导入配置 JSON 字符串
 */
export function Import(configJson: string): $CancellablePromise<void> {
    return $Call.ByID(2261309071, configJson);
}

/**
 * ListBackups 列出已有备份（真实文件系统扫描）
 */
export function ListBackups(): $CancellablePromise<$models.BackupItem[] | null> {
    return $Call.ByID(4094183809);
}

/**
 * Meta 返回文件落盘位置
 */
export function Meta(): $CancellablePromise<$models.ConfigMeta | null> {
    return $Call.ByID(178548895);
}

/**
 * Restore 从备份文件恢复配置
 */
export function Restore(path: string): $CancellablePromise<void> {
    return $Call.ByID(3338803672, path);
}

/**
 * RotateAPIKey 重新生成根密钥，返回新密钥
 */
export function RotateAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(2850242978);
}

/**
 * Update 校验并更新配置（落盘；网关运行中则热重启生效）
 */
export function Update(config: $models.GatewayConfig | null): $CancellablePromise<void> {
    return $Call.ByID(1341750955, config);
}
