// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataMigrateAPI 账号数据迁移/恢复
 * （Session 归并 / 记忆合并 / Connectors 合并，迁移前自动备份、可整体回滚）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * Backups 列出可用备份标签。
 */
export function Backups(): $CancellablePromise<string[] | null> {
    return $Call.ByID(146938536);
}

/**
 * Diagnose 诊断：当前登录身份 + 各 user_id 的数据分布 + 备份目录。
 */
export function Diagnose(): $CancellablePromise<core$0.DataMigrationDiag | null> {
    return $Call.ByID(123330905);
}

/**
 * Migrate 执行迁移：source 账号的数据并入 target（合并而非覆盖；自动备份）。
 */
export function Migrate(source: string, target: string): $CancellablePromise<core$0.DataMigrationResult | null> {
    return $Call.ByID(3380832890, source, target);
}

/**
 * Rollback 按备份标签整体还原。
 */
export function Rollback(tag: string): $CancellablePromise<void> {
    return $Call.ByID(3561156633, tag);
}
