// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GatewayAPI 网关控制API
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Restart 重启网关
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(124509837);
}

/**
 * Start 启动网关
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(2723333154);
}

/**
 * Status 获取网关状态（全部字段来自真实运行数据）
 */
export function Status(): $CancellablePromise<$models.GatewayStatus | null> {
    return $Call.ByID(1670736580);
}

/**
 * Stop 停止网关
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3570676770);
}
