// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InjectAPI 官方客户端注入（CDP 面板 / 免打扰 / 账号备份切换）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inject$0 from "../inject/models.js";

/**
 * Accounts 列出账号登录态备份
 */
export function Accounts(): $CancellablePromise<inject$0.AccountBackup[] | null> {
    return $Call.ByID(3555416909);
}

/**
 * Backup 备份当前账号登录态（name 可空，自动生成）
 */
export function Backup(name: string): $CancellablePromise<inject$0.AccountBackup | null> {
    return $Call.ByID(781956367, name);
}

/**
 * DeleteBackup 删除备份
 */
export function DeleteBackup(id: string): $CancellablePromise<void> {
    return $Call.ByID(193806764, id);
}

/**
 * GetConfig 读取注入设置
 */
export function GetConfig(): $CancellablePromise<core$0.InjectConfig> {
    return $Call.ByID(3727400453);
}

/**
 * Start 启动注入（确保客户端以调试模式运行并注入面板）
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1124641135);
}

/**
 * Status 注入运行态
 */
export function Status(): $CancellablePromise<inject$0.Status> {
    return $Call.ByID(1807412031);
}

/**
 * Stop 停止注入
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(402394549);
}

/**
 * Switch 切换到指定备份（恢复登录态并刷新客户端页面）
 */
export function Switch(id: string): $CancellablePromise<void> {
    return $Call.ByID(1736096833, id);
}

/**
 * UpdateConfig 局部更新注入设置（enabled/client_path/port/dnd_auto_confirm）
 */
export function UpdateConfig(enabled: boolean | null, clientPath: string | null, port: number | null, dnd: boolean | null): $CancellablePromise<void> {
    return $Call.ByID(3481190114, enabled, clientPath, port, dnd);
}
