// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KeysAPI 密钥管理API
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 创建密钥：生成 wb- 前缀随机明文，本机落盘明文 + SHA-256 摘要（网关鉴权仍用摘要）
 */
export function Create(params: $models.CreateKeyParams): $CancellablePromise<$models.CreateKeyResult | null> {
    return $Call.ByID(608390028, params);
}

/**
 * Delete 删除密钥
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1946023155, id);
}

/**
 * List 获取所有密钥
 */
export function List(): $CancellablePromise<$models.KeyView[] | null> {
    return $Call.ByID(2094252976);
}

/**
 * Stats 密钥用量统计：直接聚合请求日志，与「用量 / 配额」进度条同源
 */
export function Stats(id: string): $CancellablePromise<$models.KeyUsage | null> {
    return $Call.ByID(3591868171, id);
}

/**
 * Update 更新密钥配置（名称 / 配额 / 白名单 / 启停）
 * 
 * 说明：0 值视为「不修改」，因此把配额改回 0（不限）需要通过解析为 0 的显式字段——
 * 这里用指针语义之外的最简办法：只在 >0 时覆盖，0 表示不限的语义由 Disabled 之外的
 * 「不设置」承担。前端在表单里对「0 = 不限」有明确提示。
 */
export function Update(id: string, params: $models.CreateKeyParams): $CancellablePromise<void> {
    return $Call.ByID(2924032041, id, params);
}
