// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogsAPI 日志查询API
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs 清空日志（scope: request / task / credit / audit / all），返回清除条数
 */
export function ClearLogs(scope: string): $CancellablePromise<number> {
    return $Call.ByID(2913935455, scope);
}

/**
 * Export 导出日志到备份目录，返回文件绝对路径与条数
 */
export function Export(format: string, scope: string, q: $models.LogQuery): $CancellablePromise<$models.LogExportResult | null> {
    return $Call.ByID(2871432657, format, scope, q);
}

/**
 * GetAuditLogs 审计日志（管理侧敏感操作记录，时间/关键字过滤 + 分页）
 */
export function GetAuditLogs(q: $models.LogQuery): $CancellablePromise<$models.AuditLogPage | null> {
    return $Call.ByID(1572163995, q);
}

/**
 * GetCreditLogs 积分变动流水（真实余额观测差值，时间/账号过滤 + 分页）
 */
export function GetCreditLogs(q: $models.LogQuery): $CancellablePromise<$models.CreditLogPage | null> {
    return $Call.ByID(2238841455, q);
}

/**
 * GetRequestLogs 请求日志（时间范围 / 关键字 / 状态码过滤 + 分页）
 */
export function GetRequestLogs(q: $models.LogQuery): $CancellablePromise<$models.RequestLogPage | null> {
    return $Call.ByID(642196481, q);
}

/**
 * GetTaskLogs 任务日志（时间范围 / 类型 / 状态过滤 + 分页）
 */
export function GetTaskLogs(q: $models.LogQuery): $CancellablePromise<$models.TaskLogPage | null> {
    return $Call.ByID(4036215575, q);
}

/**
 * OpenExportDir 打开导出目录
 */
export function OpenExportDir(): $CancellablePromise<string> {
    return $Call.ByID(2244630404);
}
