// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelsAPI 模型清单API（聊天测试的模型选择器数据源）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * List 返回模型清单：目录收录（含 context_length / max_output_tokens）+ 本机真实用量
 */
export function List(): $CancellablePromise<core$0.ModelInfo[] | null> {
    return $Call.ByID(2258504334);
}
