// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * AccountListResult 账号列表结果（服务端分页）
 */
export interface AccountListResult {
    "items": core$0.Account[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
    "onlineCount": number;
    "authDir": string;
}

/**
 * AccountQuery 账号查询参数
 */
export interface AccountQuery {
    "keyword"?: string;
    "status"?: string;
    "realm"?: string;
    "page"?: number;
    "pageSize"?: number;

    /**
     * Sort 排序方式：credit_expiry = 积分到期优先（有到期信息的在前，
     * 按最早到期日升序；无到期信息的按余额升序排后），其余值 = 默认顺序。
     */
    "sort"?: string;
}

/**
 * ApplyParams 写入参数
 */
export interface ApplyParams {
    "target": string;
    "models": string[] | null;
}

/**
 * AuditLogPage 审计日志分页结果
 */
export interface AuditLogPage {
    "items": core$0.AuditLog[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * AwakeStatus 防休眠状态
 */
export interface AwakeStatus {
    "active": boolean;
    "note"?: string;

    /**
     * 配置里的期望值
     */
    "config": boolean;
}

/**
 * BackupItem 备份文件条目
 */
export interface BackupItem {
    "path": string;
    "name": string;
    "size": number;
    "time": string;
}

/**
 * BrowseParams 浏览参数
 */
export interface BrowseParams {
    /**
     * score(推荐) / hot(下载量) / trending(近期飙升) / newest(最近上新)
     */
    "tab": string;

    /**
     * 搜索关键词，可空
     */
    "query": string;

    /**
     * true = 绕过缓存强制拉取（页面刷新按钮）
     */
    "force": boolean;
}

/**
 * ChatParams 请求参数
 */
export interface ChatParams {
    "model": string;
    "system"?: string;
    "messages": core$0.ChatMessage[] | null;
    "temperature"?: number;
    "maxTokens"?: number;
    "stream": boolean;
    "sessionId"?: string;
}

/**
 * ChatResult 结果（含真实用量与延迟）
 */
export interface ChatResult {
    "content": string;
    "reasoning": string;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;
    "latencyFirst": number;
    "latencyTotal": number;
    "sessionId": string;
    "upstreamModel": string;

    /**
     * 用户手动停止：已生成内容有效，但未到自然结束
     */
    "aborted"?: boolean;
}

/**
 * ConfigExportResult 配置导出结果（含落盘路径）
 */
export interface ConfigExportResult {
    /**
     * 用户取消时为空
     */
    "path": string;

    /**
     * 打包的凭证份数（仅含凭证导出时 >0）
     */
    "credentials": number;
}

/**
 * ConfigMeta 配置元信息（路径等，供界面展示）
 */
export interface ConfigMeta {
    "configPath": string;
    "dataDir": string;
    "authDir": string;
    "storePath": string;
}

/**
 * CreateKeyParams 创建/更新密钥参数
 */
export interface CreateKeyParams {
    "name": string;
    "expires"?: string;
    "models"?: string[] | null;
    "ipWhitelist"?: string[] | null;
    "maxIps"?: number;
    "tokenQuota"?: number;
    "creditQuota"?: number;
    "disabled"?: boolean | null;
}

/**
 * CreateKeyResult 创建密钥结果（明文同时落盘，可在列表再次复制）
 */
export interface CreateKeyResult {
    "id": string;
    "key": string;
    "mask": string;
}

/**
 * CredentialExportResult 凭证导出结果（含落盘路径）
 */
export interface CredentialExportResult {
    /**
     * 用户取消时为空
     */
    "path": string;

    /**
     * 导出的凭证份数
     */
    "count": number;
}

/**
 * CreditDetail 任务领取积分明细
 * 
 * 口径分两本账，都展示在本页：
 *   - **确认领取**（Credits / ByTask / ByDay / Items）：只统计上游**明确返回了积分数值**
 *     的领取动作（成长任务 reward_credit / 连登档位 credit / 抽奖 credit 奖品 / 礼包补偿
 *     credit）。签到本金、开学季领奖、盲盒物品、trial 加油包等上游不返回数值的动作不写 0
 *     充数，由 Runs / NoAmount 如实计数。
 *   - **观测入账**（Observed / ObservedCredits / ObservedToday / ObservedLast7d）：积分流水
 *     里余额上升的差值条目（delta<0，含上游异步发放的签到/任务计分）。到账是事实、来源
 *     无法从响应确证，故单列且标注「来源未确证」，不与确认领取混算，也不写进 ByTask。
 * 
 * 筛选分两层，Today / Last7d / ObservedToday / ObservedLast7d 只吃第一层：
 *   - 维度筛选（UID / Type / Keyword）：确认领取三卡按它收窄；观测入账只吃 UID / Keyword
 *     （它没有任务类型，选了 Type 筛选时 Observed 返回空，前端对应隐藏）；
 *   - 时间范围（From / To）：只作用于 Credits / Runs / NoAmount / ByTask / ByDay / Items /
 *     Observed / ObservedCredits。
 */
export interface CreditDetail {
    /**
     * 今日领取（不受查询范围影响）
     */
    "today": number;

    /**
     * 近 7 天领取（含今日）
     */
    "last7d": number;

    /**
     * 查询范围内领取合计
     */
    "credits": number;

    /**
     * 查询范围内执行记录条数
     */
    "runs": number;

    /**
     * 其中未返回积分数值的条数
     */
    "noAmount": number;
    "byTask": CreditDetailTask[] | null;
    "byDay": CreditDetailDay[] | null;

    /**
     * 仅 credits > 0，新 → 旧，分页
     */
    "items": core$0.TaskLog[] | null;
    "itemHits": number;
    "page": number;
    "pageSize": number;

    /**
     * 观测入账条目（余额上升，新 → 旧，截断 50 条）
     */
    "observed": core$0.CreditLog[] | null;

    /**
     * 查询范围内观测入账合计（正数，分）
     */
    "observedCredits": number;

    /**
     * 今日观测入账（不受查询范围影响）
     */
    "observedToday": number;

    /**
     * 近 7 天观测入账（含今日）
     */
    "observedLast7d": number;
}

/**
 * CreditDetailDay 按天的领取积分汇总（本地时区，日期格式 2006-01-02）
 */
export interface CreditDetailDay {
    "date": string;
    "count": number;
    "credits": number;
}

/**
 * CreditDetailTask 按任务类型的领取积分汇总
 */
export interface CreditDetailTask {
    "type": string;

    /**
     * 有领取积分的执行次数
     */
    "count": number;

    /**
     * 累计领取积分
     */
    "credits": number;
}

/**
 * CreditLogPage 积分流水分页结果
 */
export interface CreditLogPage {
    "items": core$0.CreditLog[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * GatewayConfig 网关配置（复用 core 模型，字段与 config.json 一致）
 */
export type GatewayConfig = core$0.Config;

/**
 * GatewayStatus 网关状态（真实聚合：运行态 + 账号池 + 请求日志 + 任务状态）
 */
export interface GatewayStatus {
    "running": boolean;
    "uptime": string;
    "listen": string;
    "healthy": number;
    "total": number;
    "requests": number;
    "tokens": number;
    "todayRequests": number;
    "todayTokens": number;
    "errors": number;
    "successRate": number;
    "avgLatency": number;
    "p90": number;
    "firstLatency": number;
    "inflight": number;
    "poolOnline": number;
    "poolCooldown": number;
    "poolExpired": number;
    "poolDisabled": number;
    "poolUnknown": number;
    "tasks"?: core$0.SchedulerStatus | null;
}

/**
 * ImportResult 导入结果
 */
export interface ImportResult {
    "files": string[] | null;
    "skipped": string[] | null;
    "authDir": string;
}

/**
 * KeyUsage 单个密钥的真实用量统计（来自请求日志，非累计字段推算）
 */
export interface KeyUsage {
    "keyId": string;
    "requests": number;
    "success": number;
    "errors": number;
    "tokens": number;
    "credits": number;
    "avgLatency": number;
    "lastUsed": string;
    "byModel": ModelUsage[] | null;
}

/**
 * KeyView 密钥视图：Mask 展示脱敏串，Key 为完整明文（仅在本机管理界面展示/复制）
 */
export interface KeyView {
    "id": string;
    "name": string;
    "mask": string;
    "key"?: string;
    "created": string;
    "expires": string;
    "models": string[] | null;
    "ipWhitelist": string[] | null;
    "maxIps": number;
    "tokenQuota": number;
    "creditQuota": number;
    "tokenUsed": number;
    "creditUsed": number;
    "requests": number;
    "lastUsed": string;
    "disabled": boolean;
}

/**
 * LogExportResult 日志导出结果（含落盘路径与条数）
 */
export interface LogExportResult {
    "path": string;
    "count": number;
}

/**
 * LogQuery 日志查询参数（时间范围按 Unix 秒，服务端过滤 + 分页）
 */
export interface LogQuery {
    /**
     * Unix 秒，含
     */
    "from"?: number;

    /**
     * Unix 秒，含
     */
    "to"?: number;
    "keyword"?: string;
    "key"?: string;
    "model"?: string;
    "status"?: number;
    "statusIn"?: number[] | null;

    /**
     * 任务日志类型
     */
    "type"?: string;

    /**
     * UID 账号精确匹配。只有带账号维度的日志（任务日志）认这个字段，
     * 请求日志 / 积分流水 / 审计日志会忽略它——它们没有 uid 归属，硬凑等于假过滤。
     */
    "uid"?: string;
    "page"?: number;
    "pageSize"?: number;
}

/**
 * ModelUsage 按模型拆分的用量
 */
export interface ModelUsage {
    "model": string;
    "requests": number;
    "tokens": number;
    "errors": number;
}

/**
 * OAuthHint 授权引导
 */
export interface OAuthHint {
    "url": string;
    "authDir": string;
    "note": string;
}

/**
 * OAuthPollResult 前端轮询结果。
 * status：pending=等待登录；success=已完成；expired=授权链接过期；
 * invalid=会话丢失（应用重启过 / 没有进行中的授权）。
 */
export interface OAuthPollResult {
    "status": string;
    "uid"?: string;
    "nickname"?: string;
    "realm"?: string;

    /**
     * true=该账号已存在，本次是重新授权
     */
    "updated"?: boolean;

    /**
     * 附带说明（国际版地区注册 / trial 结果）
     */
    "note"?: string;
}

/**
 * PluginParams 安装/卸载参数（ids 仅 slash 插件使用）
 */
export interface PluginParams {
    "plugin": string;
    "ids": number[] | null;
}

/**
 * RequestLog 请求日志
 */
export type RequestLog = core$0.RequestLog;

/**
 * RequestLogPage 请求日志分页结果
 */
export interface RequestLogPage {
    "items": RequestLog[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
    "tokens": number;
    "errors": number;
}

/**
 * SkillInstallParams 安装参数
 */
export interface SkillInstallParams {
    "slug": string;
    "namespace"?: string;

    /**
     * 客户端 ID（claude-code / codex / …）
     */
    "target": string;
}

/**
 * SystemInfo 系统信息（全部为真实运行时采样值）
 */
export interface SystemInfo {
    "version": string;
    "goVersion": string;
    "platform": string;
    "arch": string;
    "numCpu": number;

    /**
     * 进程运行时长
     */
    "processUptime": string;

    /**
     * 网关运行时长（未运行则为空）
     */
    "gatewayUptime": string;

    /**
     * 当前堆分配 MB
     */
    "memoryAlloc": number;

    /**
     * 向 OS 申请的总内存 MB
     */
    "memorySys": number;
    "heapObjects": number;
    "gcCount": number;
    "goroutines": number;
}

/**
 * TaskLog 任务日志
 */
export type TaskLog = core$0.TaskLog;

/**
 * TaskLogPage 任务日志分页结果
 */
export interface TaskLogPage {
    "items": TaskLog[] | null;
    "total": number;
    "page": number;
    "pageSize": number;
}

/**
 * UpdateInfo 更新信息
 */
export interface UpdateInfo {
    "supported": boolean;
    "note": string;
    "current"?: string;
    "latest"?: string;
    "hasUpdate"?: boolean;

    /**
     * 与当前平台匹配的安装包直链
     */
    "downloadUrl"?: string;

    /**
     * Release 页面（手动下载入口）
     */
    "releasePage"?: string;

    /**
     * Release 说明（原文截断）
     */
    "releaseNotes"?: string;

    /**
     * 匹配到的安装包文件名
     */
    "assetName"?: string;

    /**
     * 该安装包是否支持应用内自动安装
     */
    "autoInstall"?: boolean;
}
