// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginsAPI 插件中心API：把 BuddyBot 能力以辅助插件形式接入编程智能体
 * （MCP 工具 / 规则同步 / 钩子 / slash 命令），全部走备份+回滚。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply 安装/更新插件
 */
export function Apply(params: $models.PluginParams): $CancellablePromise<core$0.PluginApplyResult | null> {
    return $Call.ByID(927237984, params);
}

/**
 * Backups 插件写入产生的备份列表（新→旧）
 */
export function Backups(): $CancellablePromise<core$0.PluginBackup[] | null> {
    return $Call.ByID(3195463155);
}

/**
 * DefaultSettings 插件配置的默认值（页面「恢复默认」用，避免前端再抄一份）
 */
export function DefaultSettings(): $CancellablePromise<core$0.PluginSettings | null> {
    return $Call.ByID(10146636);
}

/**
 * Remove 卸载插件
 */
export function Remove(params: $models.PluginParams): $CancellablePromise<core$0.PluginApplyResult | null> {
    return $Call.ByID(3170216732, params);
}

/**
 * Restore 回滚指定插件备份，返回恢复的文件数
 */
export function Restore(target: string, backupID: string): $CancellablePromise<number> {
    return $Call.ByID(1322526870, target, backupID);
}

/**
 * SaveSettings 保存插件配置（只落盘 plugins 段，不重启网关）
 */
export function SaveSettings($in: core$0.PluginSettings): $CancellablePromise<void> {
    return $Call.ByID(3375326324, $in);
}

/**
 * Settings 读取插件配置（规则文本 + 安全命令放行白名单）
 */
export function Settings(): $CancellablePromise<core$0.PluginSettings | null> {
    return $Call.ByID(2682885137);
}

/**
 * SlashCommands 提效指令库的安装清单（供页面做按条勾选安装/卸载）
 */
export function SlashCommands(): $CancellablePromise<core$0.PluginSlashCommand[] | null> {
    return $Call.ByID(3363557091);
}

/**
 * Statuses 所有插件的接入状态（按磁盘真实内容推导）
 */
export function Statuses(): $CancellablePromise<core$0.PluginStatus[] | null> {
    return $Call.ByID(3233120654);
}
