// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PowerAPI 防休眠控制
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SetKeepAwake 开启/关闭防休眠（同时持久化到配置，重启后保持）
 */
export function SetKeepAwake(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3763357949, on);
}

/**
 * Status 查询防休眠状态
 */
export function Status(): $CancellablePromise<$models.AwakeStatus> {
    return $Call.ByID(1486601187);
}
