// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillsAPI 技能市场API：SkillHub 技能浏览/搜索 + 安装到本机 AI 编程客户端
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Browse 浏览/搜索技能（结果按设置里的缓存时长复用，减少对 SkillHub API 的调用）
 */
export function Browse(params: $models.BrowseParams): $CancellablePromise<core$0.SkillHubBrowseResult | null> {
    return $Call.ByID(2831258644, params);
}

/**
 * Install 安装技能到指定客户端（CLI 未安装时自动先装 CLI）
 */
export function Install(params: $models.SkillInstallParams): $CancellablePromise<core$0.SkillInstallResult | null> {
    return $Call.ByID(2418592389, params);
}

/**
 * InstallCLI 自动安装 skillhub CLI（官方 install.sh --cli-only），完成后返回新状态
 */
export function InstallCLI(): $CancellablePromise<core$0.SkillHubCLIStatus> {
    return $Call.ByID(3847995753);
}

/**
 * Installed 列出某客户端已安装的技能
 */
export function Installed(target: string): $CancellablePromise<core$0.InstalledSkill[] | null> {
    return $Call.ByID(2334797452, target);
}

/**
 * Status 探测 skillhub CLI 安装状态
 */
export function Status(): $CancellablePromise<core$0.SkillHubCLIStatus> {
    return $Call.ByID(3239138304);
}

/**
 * Targets 列出可安装的客户端及其 skills 目录（含已装技能数）
 */
export function Targets(): $CancellablePromise<core$0.SkillTargetInfo[] | null> {
    return $Call.ByID(3195495476);
}

/**
 * Uninstall 卸载某客户端下的技能（前端需二次确认）
 */
export function Uninstall(target: string, dirName: string): $CancellablePromise<void> {
    return $Call.ByID(622194040, target, dirName);
}

/**
 * Update 更新单个技能到最新版（实为 --force 重装，CLI 会同步刷新版本记录）
 */
export function Update(target: string, key: string): $CancellablePromise<core$0.SkillUpdateResult | null> {
    return $Call.ByID(2616039463, target, key);
}

/**
 * UpdateAll 一键更新所有可更新的技能（跨客户端汇总后串行执行）
 */
export function UpdateAll(): $CancellablePromise<core$0.SkillUpdateResult[] | null> {
    return $Call.ByID(1423598466);
}

/**
 * Updates 检查所有客户端中经技能市场安装的技能的可更新情况（远端版本比对，结果整体缓存）
 */
export function Updates(force: boolean): $CancellablePromise<core$0.SkillUpdatesResult | null> {
    return $Call.ByID(3406220348, force);
}
