// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StatsAPI 统计聚合API。
 * 
 * 所有返回值都由真实请求日志 / 任务日志聚合而来，前后端都不做兜底填充：
 * 没有数据就是 0，能拿到什么算什么。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * Dashboard 返回近 days 天的整页统计（总览 + 逐日 + 按模型 + 按密钥 + 时段 + 任务）
 */
export function Dashboard(days: number): $CancellablePromise<core$0.Dashboard | null> {
    return $Call.ByID(4154082565, days);
}

/**
 * OfficialUsage 官方口径用量对账：拉取各在线账号最近 days 天的官方请求用量
 * （带缓存；force=true 跳过缓存）。单账号失败不影响整体，由 Source 字段标识
 * official / partial / unavailable，前端据此决定是否回退本地统计。
 */
export function OfficialUsage(days: number, force: boolean): $CancellablePromise<core$0.OfficialUsageReport | null> {
    return $Call.ByID(987958593, days, force);
}

/**
 * Overview 仅取总览（仪表盘 KPI 用，轻量）
 */
export function Overview(days: number): $CancellablePromise<core$0.Overview | null> {
    return $Call.ByID(2026676148, days);
}

/**
 * SessionDrilldown 会话下钻：缓存命中率 KPI + 会话 Top 聚合（按 token 降序）。
 */
export function SessionDrilldown(days: number): $CancellablePromise<core$0.SessionDrilldown | null> {
    return $Call.ByID(3687521894, days);
}

/**
 * SessionRequests 单个会话的请求明细（时间升序），下钻第三级。
 */
export function SessionRequests(sessionID: string, days: number): $CancellablePromise<core$0.RequestLog[] | null> {
    return $Call.ByID(1971807603, sessionID, days);
}
