// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemAPI 系统信息API
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate 检查更新：查询 GitHub Releases 最新发布，按当前平台挑选安装包。
 * 
 * 更新通道由构建期 ldflags 注入（updateRepo）；未配置时如实返回「不支持」，
 * 不返回看起来像真的版本号。这是检测 + 手动更新：下载安装包到本地缓存目录，
 * 由用户执行安装——桌面端静默替换自身进程需要平台专属机制，不在本步范围内。
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(953389778);
}

/**
 * DownloadUpdate 下载指定安装包到本地更新缓存目录，返回落盘绝对路径。
 * 仅允许下载 CheckUpdate 返回的 GitHub Release 直链（防 SSRF / 任意文件写）；
 * 下载过程推送 update:progress 进度事件，完成后按 Release 内 checksums.txt 做 sha256 校验。
 */
export function DownloadUpdate(downloadURL: string): $CancellablePromise<string> {
    return $Call.ByID(2008510892, downloadURL);
}

/**
 * GetInfo 获取系统信息（runtime 真实采样）
 */
export function GetInfo(): $CancellablePromise<$models.SystemInfo | null> {
    return $Call.ByID(591818135);
}

/**
 * InstallUpdate 安装已下载并校验通过的更新包（DownloadUpdate 返回的路径），
 * 随后退出应用并由平台专属机制完成替换/重启。仅接受更新缓存目录内的文件，
 * 防止任意路径执行。
 */
export function InstallUpdate(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(2201827173, filePath);
}

/**
 * SendTestNotify 发送桌面测试通知（macOS 首次调用会触发系统授权弹窗）。
 * 未打包（go run / 裸二进制）时如实返回不可用，不假装成功。
 */
export function SendTestNotify(): $CancellablePromise<void> {
    return $Call.ByID(3108330450);
}
