// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account 账号视图：凭证文件（身份/凭证事实）+ 本地运行态（余额/冷却/活动）合并结果。
 */
export interface Account {
    "uid": string;
    "nickname": string;
    "domain": string;
    "realm": string;
    "enterpriseId": string;
    "credential": string;

    /**
     * online / cooldown / expired / unknown / disabled / invalid
     */
    "status": string;
    "tokenExpiry": string;

    /**
     * 剩余秒；<0 已过期
     */
    "expiresIn": number;
    "hasToken": boolean;
    "hasRefresh": boolean;
    "credits": number;
    "creditsKnown": boolean;
    "creditsUsed"?: number;

    /**
     * 72h 内到期的剩余积分
     */
    "creditsExpiring"?: number;
    "lastCheckin": string;
    "lastActivity": string;
    "cooldownUntil": string;
    "failStreak": number;
    "inflight": number;
    "needsRelogin"?: boolean;

    /**
     * 最早积分到期日（YYYY-MM-DD，来自真实余额巡检）
     */
    "creditsExpireDay"?: string;

    /**
     * 该到期日的剩余积分
     */
    "creditsExpireRemain"?: number;
    "note"?: string;
}

/**
 * AgentApplyResult 写入结果
 */
export interface AgentApplyResult {
    "target": string;
    "backupDir": string;
    "files": string[] | null;
    "models": string[] | null;
}

/**
 * AgentBackup 一份备份（备份目录下的时间戳子目录）
 */
export interface AgentBackup {
    "id": string;
    "files": string[] | null;
}

/**
 * AgentTarget 单个客户端的探测结果
 */
export interface AgentTarget {
    "id": string;
    "name": string;
    "configPath": string;
    "installed": boolean;
    "configured": boolean;
    "note"?: string;
}

/**
 * AuditLog 审计日志（管理侧敏感操作记录）。
 */
export interface AuditLog {
    "id": string;
    "ts": number;
    "time": string;

    /**
     * config.update / key.create / account.delete ...
     */
    "action": string;
    "target"?: string;
    "detail"?: string;
}

/**
 * ChatMessage 消息
 */
export interface ChatMessage {
    "role": string;
    "content": string;
}

/**
 * ClientSwitchPrecheck 切换前检查结果（前端据此渲染确认信息）
 */
export interface ClientSwitchPrecheck {
    "uid": string;
    "nickname": string;
    "targetRealm": string;
    "officialAuthFile": string;
    "officialExists": boolean;

    /**
     * 当前官方登录区域（解析失败为空）
     */
    "officialRealm": string;
    "clientFound": boolean;
    "clientPath": string;
    "clientRunning": boolean;
    "backupDir": string;
    "warnings"?: string;
}

export interface Config {
    "listen": string;
    "api_key": string;
    "auth_dir": string;
    "state_file": string;
    "schedule": ScheduleConfig;
    "pool": PoolConfig;
    "security": SecurityConfig;
    "session_sticky": SessionConfig;
    "prompt": PromptConfig;
    "models": ModelsConfig;
    "redis": RedisConfig;
    "keep_awake": boolean;
    "inject": InjectConfig;
    "skillhub": SkillHubConfig;
}

/**
 * CreditLog 积分变动流水（真实余额查询之间的差值，非估算）。
 */
export interface CreditLog {
    "id": string;
    "ts": number;
    "time": string;
    "uid": string;

    /**
     * 变动量（正 = 消耗，负 = 增加）
     */
    "delta": number;

    /**
     * 变动后余额
     */
    "balance": number;
    "note"?: string;
}

/**
 * Dashboard 统计聚合结果（一次调用返回整页所需数据）
 */
export interface Dashboard {
    "rangeSecs": number;
    "overview": Overview;
    "daily": TrendPoint[] | null;
    "models": ModelStat[] | null;
    "keys": KeyStat[] | null;
    "hourly": HourStat[] | null;
    "tasks": TaskStat[] | null;

    /**
     * HeatmapDays / Heatmap 逐日 20 分钟粒度 token 矩阵（行 = 天，列 = 72 个 20 分钟桶）
     */
    "heatmapDays": string[] | null;
    "heatmap": (number[] | null)[] | null;
    "dailyModels": DayModelStat[] | null;
}

/**
 * DataMigrationDiag 诊断结果。
 */
export interface DataMigrationDiag {
    /**
     * 当前登录（DB 最新 session 推断，可能为空）
     */
    "currentUid": string;
    "users": UserFootprint[] | null;
    "backupDir": string;
    "dbPath": string;
}

/**
 * DataMigrationResult 迁移执行结果。
 */
export interface DataMigrationResult {
    "backupTag": string;
    "sessionsMoved": number;

    /**
     * 追加的记忆行数（0 = 无新增或无源文件）
     */
    "memoryAppended": number;

    /**
     * 增量拷贝的 Connector 文件数
     */
    "connectorCopied": number;
    "note"?: string;
}

/**
 * DayModelStat 单日按模型拆分
 */
export interface DayModelStat {
    "date": string;
    "byModel": { [_ in string]?: number } | null;
}

/**
 * HourStat 0-23 时段聚合（按模型拆分，供山脊图使用）
 */
export interface HourStat {
    "hour": number;
    "requests": number;
    "tokens": number;
    "byModel": { [_ in string]?: number } | null;
}

/**
 * Config 网关配置（字段命名对齐 workbuddy2api config.json）
 * InjectConfig 官方客户端注入（CDP）设置
 */
export interface InjectConfig {
    "enabled": boolean;

    /**
     * 官方客户端可执行文件路径；留空自动探测（/Applications 下 WorkBuddy*.app 等）
     */
    "client_path": string;

    /**
     * CDP 调试端口（避开常用 9222）
     */
    "port": number;

    /**
     * 权限弹窗免打扰：自动点击确认类按钮
     */
    "dnd_auto_confirm": boolean;

    /**
     * 增强开关（注入面板「设置」Tab 可控制，按弹窗/页面文本启发式匹配）
     * 沙箱外写文件免确认
     */
    "allow_file_write": boolean;

    /**
     * 常用命令行免确认
     */
    "allow_commands": boolean;

    /**
     * 大批量删除免确认
     */
    "allow_batch_delete": boolean;

    /**
     * 系统级工具放行
     */
    "allow_system_tools": boolean;

    /**
     * 继续异常中断会话
     */
    "auto_resume_session": boolean;

    /**
     * 引用消息文本
     */
    "quote_message": boolean;

    /**
     * 会话消息索引（悬浮定位条）
     */
    "message_nav": boolean;

    /**
     * 主题（注入面板「主题」Tab，作用于 WorkBuddy 本体换肤；ID 为空=从未设置，不注入）
     */
    "theme": ThemeConfig;

    /**
     * 宠物（注入面板悬浮机器人皮肤；"" = 经典 CSS 机器人）
     */
    "pet": string;
}

/**
 * InstalledSkill 已安装技能（扫描目标目录）
 */
export interface InstalledSkill {
    "dirName": string;
    "name": string;
    "description": string;
    "path": string;
}

/**
 * KeyStat 单密钥聚合
 */
export interface KeyStat {
    "keyId": string;
    "keyName": string;
    "requests": number;
    "tokens": number;
    "errors": number;
    "avgLatency": number;
}

/**
 * ModelInfo 模型清单条目（静态能力 + 本机真实用量）
 */
export interface ModelInfo {
    "id": string;
    "contextLength": number;
    "maxOutputTokens": number;

    /**
     * catalog = 目录收录；observed = 仅本机观测到
     */
    "source": string;

    /**
     * 是否在本机请求日志中出现过
     */
    "observed": boolean;
    "requests": number;
    "tokens": number;
}

/**
 * ModelStat 单模型聚合
 */
export interface ModelStat {
    "model": string;
    "requests": number;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;

    /**
     * 上游 usage 命中缓存的输入 token
     */
    "cacheTokens": number;
    "errors": number;
    "avgLatency": number;
    "p50": number;
    "p90": number;
    "p99": number;

    /**
     * 单次请求平均 token
     */
    "avgTokens": number;

    /**
     * 单次请求大小分位
     */
    "tokenP50": number;
    "tokenP90": number;
}

/**
 * ModelsConfig 模型中心：别名映射 / 积分倍率 / 分组
 */
export interface ModelsConfig {
    /**
     * 客户端可见模型名 → 上游真实模型名
     */
    "aliases": { [_ in string]?: string } | null;

    /**
     * 积分倍率：每 1k token 基准 1 分 × rate（0 = 免费）
     */
    "rates": { [_ in string]?: number } | null;

    /**
     * 模型 → 分组名（展示用）
     */
    "groups": { [_ in string]?: string } | null;
}

/**
 * NextRun 排程的下次执行时间
 */
export interface NextRun {
    "type": string;
    "enabled": boolean;
    "hours": number[] | null;

    /**
     * RFC3339；空 = 已禁用
     */
    "next": string;
}

/**
 * NotifyConfig 任务完成推送通知配置
 */
export interface NotifyConfig {
    /**
     * 总开关
     */
    "enabled": boolean;

    /**
     * 仅在有失败时推送
     */
    "only_failures": boolean;

    /**
     * PushPlus token（空 = 不用 PushPlus）
     */
    "pushplus_token": string;

    /**
     * Bark 地址（形如 https://api.day.app/你的key，空 = 不用 Bark）
     */
    "bark_url": string;

    /**
     * Desktop 系统级桌面通知（通知中心横幅，覆盖账号掉线 / 错误类事件）。
     * 指针语义：存量配置缺字段视为开启（nil = 开），仅用户显式关闭后落盘为 false。
     */
    "desktop"?: boolean | null;
}

/**
 * OfficialUsageAccount 单账号官方用量聚合
 */
export interface OfficialUsageAccount {
    "uid": string;
    "nickname": string;
    "realm": string;
    "today": number;
    "total": number;
    "requests": number;
    "daily": OfficialUsageDay[] | null;
    "models": OfficialUsageModel[] | null;

    /**
     * 该账号拉取失败原因（不影响其他账号）
     */
    "error"?: string;
}

/**
 * OfficialUsageDay 单日官方用量
 */
export interface OfficialUsageDay {
    /**
     * YYYY-MM-DD
     */
    "date": string;
    "requests": number;
    "credits": number;
}

/**
 * OfficialUsageModel 单模型官方用量
 */
export interface OfficialUsageModel {
    "model": string;
    "requests": number;
    "credits": number;
}

/**
 * OfficialUsageReport 官方用量对账报告
 */
export interface OfficialUsageReport {
    "fetchedAt": string;
    "days": number;

    /**
     * official = 官方接口；partial = 部分账号失败
     */
    "source": string;
    "accounts": OfficialUsageAccount[] | null;
}

/**
 * Overview 总览指标
 */
export interface Overview {
    "requests": number;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;
    "cacheTokens": number;
    "errors": number;
    "successRate": number;
    "avgLatency": number;
    "firstLatency": number;
    "p50": number;
    "p90": number;
    "p99": number;
    "sessions": number;
    "days": number;
    "avgPerDay": number;
    "peakDate": string;
    "peakTokens": number;
    "todayTokens": number;
    "todayRequests": number;
    "accountsTotal": number;
    "accountsOnline": number;
    "keysTotal": number;
    "creditsTotal": number;
    "creditsUnknown": number;
    "firstTs": number;
    "lastTs": number;
}

/**
 * PoolConfig 账号池策略配置
 */
export interface PoolConfig {
    "max_in_flight": number;
    "breaker_threshold": number;
    "breaker_cooldown": string;
    "cooldown_max": string;

    /**
     * CostExploreInterval 成本探索间隔（形如 30m；空/0 = 关闭）。
     * 已观测到免费成本的账号层每间隔一段时间放行一次未观测账号，搭车探索真实成本。
     */
    "cost_explore_interval": string;
}

/**
 * PromptConfig 系统提示词三模式（对齐 workbuddy2api prompt.mode）
 */
export interface PromptConfig {
    /**
     * passthrough 透传 / custom 替换 / append 追加
     */
    "mode": string;

    /**
     * custom/append 使用的系统提示词
     */
    "text": string;
}

/**
 * RedisConfig 可选状态镜像（Upstash REST）：会话粘性绑定 + 状态快照
 */
export interface RedisConfig {
    "enabled": boolean;

    /**
     * 形如 https://xxx.upstash.io
     */
    "url": string;
    "token": string;
}

/**
 * RefreshConfig 定时刷新配置
 */
export interface RefreshConfig {
    "enabled": boolean;

    /**
     * IntervalMinutes 刷新间隔（分钟）；0 = 默认 30 分钟
     */
    "interval_minutes": number;
}

/**
 * RequestLog 请求日志（网关真实记录，非估算）。
 */
export interface RequestLog {
    "id": string;

    /**
     * Unix 秒，聚合口径
     */
    "ts": number;
    "time": string;
    "keyName": string;
    "keyId": string;
    "model": string;
    "status": number;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;

    /**
     * 上游 usage 命中的缓存 token（未报为 0）
     */
    "cacheTokens"?: number;

    /**
     * 总耗时 ms
     */
    "latency": number;

    /**
     * 首字节耗时 ms
     */
    "firstLatency": number;
    "ip": string;
    "sessionId": string;
    "stream": boolean;
    "error"?: string;
}

/**
 * ScheduleConfig 定时任务配置
 */
export interface ScheduleConfig {
    "checkin_hours": number[] | null;
    "travel_hours": number[] | null;
    "keepalive_hours": number[] | null;
    "checkin_enabled": boolean;
    "travel_enabled": boolean;
    "keepalive_enabled": boolean;

    /**
     * 扩展任务（对齐 workbuddy2api schedule.*_hours/*_enabled）
     * 活跃地图（上报活跃事件）
     */
    "activity_hours": number[] | null;
    "activity_enabled": boolean;

    /**
     * 开学季活动（仅 CN）
     */
    "school_hours": number[] | null;
    "school_enabled": boolean;

    /**
     * 夜猫子任务（23:00-08:00 窗口，仅 CN）
     */
    "cat_hours": number[] | null;
    "cat_enabled": boolean;

    /**
     * RunBudgetMinutes 单轮任务时间预算（分钟）：超预算后剩余账号直接跳过，
     * 防止成长任务等长流程跑穿占用整个调度窗口（对齐 auto-signin 时间预算）。
     * 0 = 默认 10 分钟；负数 = 不限制。
     */
    "run_budget_minutes": number;

    /**
     * Refresh 定时刷新：按固定间隔自动刷新需要手工刷新的内容
     * （账号积分余额 + 模型目录），把「查余额 / 深度刷新」交给调度器定时做。
     */
    "refresh": RefreshConfig;

    /**
     * Notify 推送通知（对齐 workbuddy2api notify.*）
     */
    "notify": NotifyConfig;
}

/**
 * SchedulerStatus 调度器运行态
 */
export interface SchedulerStatus {
    "running": boolean;
    "nextRuns": NextRun[] | null;
    "lastRun"?: TaskRun | null;
    "history": TaskRun[] | null;

    /**
     * 正在执行中的任务类型（手动/排程共用）
     */
    "busy": string[] | null;
}

/**
 * SecurityConfig 网关安全设置
 */
export interface SecurityConfig {
    "require_ip_allowlist": boolean;
    "ip_whitelist": string[] | null;

    /**
     * CIDR 黑名单，命中直接拒绝（优先于白名单）
     */
    "ip_blacklist": string[] | null;

    /**
     * 只读模式：管理侧一切变更被拒绝
     */
    "read_only": boolean;
}

/**
 * SessionConfig 会话粘性配置
 */
export interface SessionConfig {
    "enabled": boolean;
    "ttl": string;
}

/**
 * SessionDrilldown 会话下钻结果：缓存命中率 KPI + 会话聚合列表。
 */
export interface SessionDrilldown {
    "days": number;

    /**
     * 窗口内输入侧总量（含缓存命中部分）
     */
    "inputTokens": number;

    /**
     * 窗口内缓存命中 token
     */
    "cacheTokens": number;

    /**
     * 缓存命中率 %（cache / input × 100；无输入为 0）
     */
    "cacheHitRate": number;

    /**
     * 按 token 降序，Top 20
     */
    "sessions": SessionStat[] | null;
}

/**
 * SessionStat 会话级聚合（keyName → sessionID → 请求 的下钻中间层）。
 * 项目维度：请求日志只携带调用方传入的 session_id，没有项目/工作空间字段，
 * 因此下钻链路为「密钥（调用方）→ 会话 → 请求」，不做任何推测性归属。
 */
export interface SessionStat {
    "sessionId": string;
    "keyName": string;
    "firstTs": number;
    "lastTs": number;
    "requests": number;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;
    "cacheTokens": number;
    "errors": number;
}

/**
 * SkillHubBrowseResult 浏览结果
 */
export interface SkillHubBrowseResult {
    "tab": string;
    "query": string;
    "skills": SkillHubSkill[] | null;

    /**
     * 榜单需要 CLI，缺失时降级为搜索接口
     */
    "cliMissing": boolean;

    /**
     * 数据拉取时间（毫秒时间戳，用于前端展示缓存年龄）
     */
    "fetchedAt": number;

    /**
     * 本次响应是否来自缓存
     */
    "fromCache": boolean;
}

/**
 * SkillHubCLIStatus skillhub CLI 安装状态
 */
export interface SkillHubCLIStatus {
    "installed": boolean;
    "version"?: string;
    "path"?: string;
}

/**
 * SkillHubConfig SkillHub 技能市场配置
 */
export interface SkillHubConfig {
    /**
     * CacheTTLMinutes 市场数据（浏览列表 / 更新检查）缓存时长（分钟）。
     * 缓存期内同请求直接复用，减少对 SkillHub API 的调用防封禁；0 = 默认 3 天。
     * 页面「刷新 / 重新检查」始终绕过缓存强制拉取。
     */
    "cache_ttl_minutes": number;
}

/**
 * SkillHubSkill 技能条目（搜索/榜单统一归一化后的形态）
 */
export interface SkillHubSkill {
    "slug": string;
    "name": string;
    "namespace"?: string;
    "description": string;
    "category"?: string;
    "version"?: string;
    "source"?: string;
    "iconUrl"?: string;
    "downloads": number;
    "installs": number;
    "stars": number;
    "score": number;
    "requiresApiKey": boolean;
    "updatedAt": number;
}

/**
 * SkillInstallResult 安装结果
 */
export interface SkillInstallResult {
    "slug": string;
    "namespace"?: string;
    "target": string;
    "dir": string;
    "output": string;
}

/**
 * SkillTargetInfo 可安装的客户端及其 skills 目录
 */
export interface SkillTargetInfo {
    "id": string;
    "name": string;
    "dir": string;

    /**
     * 客户端本身是否已安装（配置目录存在）
     */
    "installed": boolean;

    /**
     * 目录下已装技能数
     */
    "count": number;
}

/**
 * SkillUpdateItem 可更新的技能（CLI 通过 lockfile 安装的技能才能检测版本）
 */
export interface SkillUpdateItem {
    /**
     * lockfile 键，如 @user_865e3592/ui-new
     */
    "key": string;

    /**
     * 客户端 ID
     */
    "target": string;
    "targetName": string;
    "slug": string;

    /**
     * namespace handle，用于 --namespace 精确安装
     */
    "namespace": string;
    "name": string;
    "description": string;
    "installedVersion": string;
    "latestVersion": string;
    "hasUpdate": boolean;

    /**
     * 无法检测时的说明（未收录 / 查询失败等）
     */
    "note"?: string;
}

/**
 * SkillUpdateResult 单个技能的更新执行结果
 */
export interface SkillUpdateResult {
    "key": string;
    "target": string;
    "ok": boolean;
    "fromVersion"?: string;
    "toVersion"?: string;
    "message"?: string;
}

/**
 * SkillUpdatesResult 更新检查结果（整体缓存：每次检查对每个技能发一次 API 请求）
 */
export interface SkillUpdatesResult {
    "items": SkillUpdateItem[] | null;

    /**
     * 检查时间（毫秒时间戳）
     */
    "fetchedAt": number;
    "fromCache": boolean;
}

/**
 * TaskLog 任务日志（调度器 / 手动触发的真实执行记录）。
 */
export interface TaskLog {
    "id": string;
    "ts": number;
    "time": string;

    /**
     * checkin / travel / keepalive / activity / school / cat / growth
     */
    "type": string;

    /**
     * manual / schedule
     */
    "trigger": string;
    "uid": string;

    /**
     * success / failed / skipped
     */
    "status": string;
    "message": string;

    /**
     * 耗时 ms
     */
    "duration": number;
}

/**
 * TaskRun 一次任务运行的真实结果
 */
export interface TaskRun {
    "type": string;

    /**
     * manual / schedule
     */
    "trigger": string;
    "startedAt": string;

    /**
     * ms
     */
    "duration": number;
    "total": number;
    "success": number;
    "failed": number;
    "skipped": number;
    "details": TaskRunDetail[] | null;
}

/**
 * TaskRunDetail 单账号执行明细
 */
export interface TaskRunDetail {
    "uid": string;
    "status": string;
    "message": string;
}

/**
 * TaskStat 任务类型聚合
 */
export interface TaskStat {
    "type": string;
    "total": number;
    "success": number;
    "failed": number;
    "skipped": number;
}

/**
 * ThemeConfig WorkBuddy 换肤状态（对齐 WorkDaddy 主题页的能力面）
 */
export interface ThemeConfig {
    /**
     * default/dark/eye-care/cyber-purple/glass
     */
    "id": string;

    /**
     * ""无 / "preset:wallpaper-01" / "custom:<文件名>"
     */
    "wallpaper": string;

    /**
     * 背景蒙版 0-100（壁纸压暗）
     */
    "mask": number;

    /**
     * 背景毛玻璃 0-100（壁纸模糊）
     */
    "blur": number;

    /**
     * 消息文字阴影（壁纸可读性增强）
     */
    "text_shadow": boolean;
}

/**
 * TrendPoint 单日聚合
 */
export interface TrendPoint {
    /**
     * MM-DD
     */
    "date": string;
    "requests": number;
    "tokens": number;
    "inputTokens": number;
    "outputTokens": number;

    /**
     * 上游 usage 命中缓存的输入 token
     */
    "cacheTokens": number;
    "errors": number;
    "avgLatency": number;
}

/**
 * UserFootprint 单个 user_id 在本机的数据分布。
 */
export interface UserFootprint {
    "uid": string;
    "sessions": number;
    "memory": boolean;
    "connectors": boolean;
}
