// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountBackup 账号登录态备份（官方登录文件快照；legacy 条目为 localStorage 快照）
 */
export interface AccountBackup {
    /**
     * 文件名（去扩展名）
     */
    "id": string;

    /**
     * 用户备注名
     */
    "name": string;

    /**
     * 自动识别的账号标识（识别失败为空）
     */
    "uid": string;

    /**
     * 备份账号区域（cn/global）
     */
    "realm"?: string;

    /**
     * 备份时间
     */
    "time": string;

    /**
     * 字节数
     */
    "size": number;
}

/**
 * Status 当前注入运行态
 */
export interface Status {
    "running": boolean;
    "target"?: string;
    "port"?: number;
    "since"?: string;
    "dnd": boolean;
}
